packages:
  - apps/*
  - packages/*
catalog:
  "@eslint/js": ^9.34.0
  "@next/eslint-plugin-next": ^15.5.0
  "@types/node": ^22.15.3
  "@types/react": 19.1.0
  "@types/react-dom": 19.1.1
  eslint: ^9.34.0
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.0
  globals: ^16.3.0
  next: ^15.5.0
  prettier: ^3.6.2
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript-eslint: ^8.40.0

catalogs:
  turbo:
    turbo: 2.5.8
